version: '2'

services:
    ercore_c7:
        image: ercore_c7:v2.1
        build:
            context: .
            dockerfile: Dockerfile_c7
        tty: true
        dns: 8.8.8.8
        volumes:
            - /home/metocean/ercore:/home/newuser/ercore
        environment:
           - DISPLAY=192.168.1.7:0
        user: newuser
        container_name : ercore_c7
        # mem_limit: 4000000000

